spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root2
    url: jdbc:mysql://localhost:3306/apitest?serverTimezone=GMT%2b8
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml

